Added GET, POST and PATCH to database with validation and authentication
NDLANO/concept-api pull request #4
Opened 2019-06-27 12:09 UTC by N4G1

2019-06-28 07:39 UTC, talepre reviewed
Hvis det går an kan man gjerne lage mindre pull-requests, f.eks en etter man laget GET, en etter POST, en etter PATCH osv. Gjør det enklere å gi gode reviews :)

2019-06-28 07:39 UTC, talepre commented on src/main/scala/no/ndla/conceptapi/auth/Role.scala
> + * Copyright (C) 2017 NDLA
2019

2019-06-28 07:39 UTC, talepre commented on src/main/scala/no/ndla/conceptapi/auth/UserInfo.scala
> + * Copyright (C) 2018 NDLA
2019

2019-06-28 07:39 UTC, talepre commented on src/main/scala/no/ndla/conceptapi/model/api/UpdatedConcept.scala
> +                            "Available titles for the concept") title: Option[
Her er det vel bare en tittel ikke flere?

2019-06-28 07:39 UTC, talepre commented on src/main/scala/no/ndla/conceptapi/repository/ConceptRepository.scala
> +//    private def conceptsWhereA(whereClause: SQLSyntax)(
Gjerne slett metoder hvis de ikke brukes/skal brukes snart.

2019-06-28 12:08 UTC, gunnarvelle requested changes
Skulle også gjerne hatt tester, men det kjem vel etter kvart.

2019-06-28 12:08 UTC, gunnarvelle commented on src/main/scala/no/ndla/conceptapi/ConceptApiProperties.scala
> +  val ArticleApiHost: String =
Ser ikkje for meg at det trengs koblinger til alle disse andre tjenestene. image-api og search-api kanskje, men ikkje learningpath eller audio i det minste.

2019-06-28 12:08 UTC, gunnarvelle commented on src/main/scala/no/ndla/conceptapi/DBMigrator.scala
> +      .table("schema_version") // Flyway's default table name changed, so we specify the old one.
Her er det jo en ny database. Kanskje vi ikkje treng å spesifisere dette her?

2019-06-28 12:08 UTC, gunnarvelle commented on src/main/scala/no/ndla/conceptapi/model/api/NewAgreementCopyright.scala
> +@ApiModel(description = "Description of agreement copyright information")
Burde endre denne til å heite NewCopyright og fjerne referanser til artikler og avtaler-

2019-06-28 12:08 UTC, gunnarvelle commented on src/main/scala/no/ndla/conceptapi/model/domain/Content.scala
> +case class Concept(id: Option[Long],
Filnavnet kan være Concept så lenge du ikkje har andre klasser inni her.

2019-06-28 12:58 UTC, jnatten commented on src/main/scala/no/ndla/conceptapi/model/api/NewAgreementCopyright.scala
> +@ApiModel(description = "Description of agreement copyright information")
Hele denne filen kan egentlig slettes. `NewConcept` bruker den vanlige `Copyright` api klassen.

2019-06-28 13:53 UTC, gunnarvelle approved these changes
LGTM. Berre lag mindre pull requester i framtida.

2019-07-01 06:44 UTC, talepre approved these changes

2019-07-01 07:08 UTC, jnatten approved these changes

2019-07-01 07:09 UTC, merged