implemented the possibility to delete metaImage and added tests
NDLANO/concept-api pull request #40
Opened 2020-03-25 14:35 UTC by N4G1

Legge til fjerning av metabilde fra forklaring #2011

2020-03-25 14:38 UTC, N4G1 commented on src/test/scala/no/ndla/conceptapi/controller/ConceptControllerTest.scala
> +      verify(writeService, times(2)).updateConcept(1, missingExpected)
Skjønner ikke helt hvorfor`sbt fmt` invoker denne 2 ganger, mens når jeg tester i intellij så vil den invoke 1 gang. Funksjonaliteten er helt den samme som i testen over og den fungerer med bare 1 invoke både i intellij og i sbt, what gives?

2020-03-26 06:26 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/controller/ConceptControllerTest.scala
> +      verify(writeService, times(2)).updateConcept(1, missingExpected)
Antar du mener `sbt test`? Håper ikke formatering invoker noe :smile: 
Jeg tipper at den invokes 2 ganger i intellij også om du kjører alle testene.
Den ser på antall ganger den har blitt invoket på mocken totalt.

`reset(writeService)` vil resette kall (og alle stubbinger) på mocken.

2020-03-26 07:05 UTC, N4G1 commented on src/test/scala/no/ndla/conceptapi/controller/ConceptControllerTest.scala
> +      verify(writeService, times(2)).updateConcept(1, missingExpected)
Wow, yes mente selvfølgelig `sbt test` kek, men hvis testene påvirker hverandre, hvorfor er det bare den første verify (av 3) som blir påvirka da? de andre passer med 1 invokation og når jeg prøvde bytte de til 2 så tryna testen. What gives?

2020-03-26 07:12 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/controller/ConceptControllerTest.scala
> +      verify(writeService, times(2)).updateConcept(1, missingExpected)
Tipper at parameterene du forventer i verify funksjonen de andre stedene er forskjellige, men den som kjører 2 ganger forventer de samme et en annen test.

2020-03-26 07:15 UTC, N4G1 commented on src/test/scala/no/ndla/conceptapi/controller/ConceptControllerTest.scala
> +      verify(writeService, times(2)).updateConcept(1, missingExpected)
Det kan faktisk stemme.

2020-03-26 07:44 UTC, N4G1 commented on src/test/scala/no/ndla/conceptapi/controller/ConceptControllerTest.scala
> +      verify(writeService, times(2)).updateConcept(1, missingExpected)
Er koden OK ellers?

2020-03-26 09:21 UTC, jnatten requested changes

2020-03-26 09:21 UTC, jnatten commented on src/main/scala/no/ndla/conceptapi/model/api/UpdatedConcept.scala
> +      Option[NewConceptMetaImage]], // We use this type to make json4s understand the difference between null and missing fields
Om vi skal gjøre dette flere enn 1 sted og kommentere det hver gang så stemmer jeg for at vi lager en type for det, feks i pakke objektet og kommenterer det der.
```suggestion
    @(ApiModelProperty @field)(description = "An image-api ID for the concept meta image") metaImage: Deletable[NewConceptMetaImage],
```
Så kan du definere typen i pakke objektet e.l:
`type Deletable[T] = Either[Null, Option[T]]`

2020-03-26 09:21 UTC, jnatten commented on src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
> +      }
Det her er vel feil. Det her vil slette metaImage for alle språk dersom man sender inn `Left(_)`?

Unngå å bruke `.get` om mulig, det kan kaste exceptions om optionen er `None`.
Vi kan også la `mergeLanguageFields` håndtere manglende felt slik som tidligere.


```suggestion
      val newMetaImage = updateConcept.metaImage match {
        case Left(_) => toMergeInto.metaImage.filterNot(_.language == updateConcept.language)
        case Right(meta) =>
          val domainMetaImage = meta
            .map(m => domain.ConceptMetaImage(m.id, m.alt, updateConcept.language))
            .toSeq
          mergeLanguageFields(toMergeInto.metaImage, domainMetaImage)
      }
```

2020-03-26 09:21 UTC, jnatten commented on src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
> +      }
Samme med `.get` her:
Gjør noe sånt:
```suggestion
      val newMetaImage = concept.metaImage.toSeq
        .flatMap(meta => meta.map(m => domain.ConceptMetaImage(m.id, m.alt, lang)))
```
Eller sånt: :smile: 
```suggestion
      val newMetaImage = concept.metaImage match {
        case Right(meta) => meta.map(m => domain.ConceptMetaImage(m.id, m.alt, lang)).toSeq
        case Left(_)     => Seq.empty
      }
```

2020-03-26 09:21 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/service/ConverterServiceTest.scala
> +      )
Egner seg nok å lage en kopi på både input og output.
Da kan `TestData.domainConcept` endre seg uten at denne testen påvirkes. I tillegg er det mye tydeligere hvordan metaImage skal se ut før og etter.

(Denne skulle ikke vært en tom liste etterpå da `TestData.domainConcept` har metaImage på flere språk)

2020-03-26 09:21 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/service/ConverterServiceTest.scala
> +    service.toDomainConcept(TestData.domainConcept, updateWith) should be(
Denne testen er riktig, men liker som jeg nevnte tidligere å lage en kopi på input også

2020-03-27 05:58 UTC, jnatten approved these changes
:100:

2020-03-29 09:33 UTC, merged