Implemented tests for ConceptRepository class
NDLANO/concept-api pull request #5
Opened 2019-06-28 12:52 UTC by katrinewi

2019-06-28 13:57 UTC, gunnarvelle commented on src/test/scala/no/ndla/conceptapi/repository/ConceptRepositoryTest.scala
> +  test("Updating an concept should work as expected") {
Her tester du forsåvidt både insert og update, så beskrivelsen kunne beskrevet det.

2019-06-28 13:58 UTC, gunnarvelle approved these changes
LGTM.

Men fullfør PR#4 først og merge deretter master inn i denne branchen. No er det masse duplikat kode i disse pull requestene.

2019-07-01 07:44 UTC, jnatten requested changes

2019-07-01 07:44 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/TestData.scala
> +  //  val userWithPublishAccess = UserInfo("unit test", Set(Role.WRITE, Role.SET_TO_PUBLISH))
Disse finnes ikke i concept-api så de kan fjernes :)

2019-07-01 07:44 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/TestEnvironment.scala
> + * Part of NDLA draft_api.
:cactus:

2019-07-01 07:44 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/TestData.scala
> + * Part of NDLA draft_api.
:cactus:

2019-07-01 07:44 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/IntegrationSuite.scala
> + * Part of NDLA draft_api.
:cactus:

2019-07-01 07:44 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/UnitSuite.scala
> + * Part of NDLA draft_api.
:cactus:

2019-07-01 07:44 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/repository/ConceptRepositoryTest.scala
> +package no.ndla.conceptapi.repository
Mangler header :)

2019-07-01 08:03 UTC, talepre commented on src/test/scala/no/ndla/conceptapi/IntegrationSuite.scala
> + * Copyright (C) 2017 NDLA
2019, gjelder nedover her også

2019-07-01 08:18 UTC, jnatten approved these changes
LGTM

2019-07-01 10:15 UTC, merged