2376 legge til flere artikler i forklaring
NDLANO/concept-api pull request #71
Opened 2020-12-29 12:21 UTC by haattis

2020-12-30 10:12 UTC, gunnarvelle reviewed
Ser bra ut men vil gjerne at @jnatten ser over denne også i tilfelle eg har oversett nokke.

2020-12-30 10:12 UTC, gunnarvelle commented on src/main/scala/db/migration/V7__ConceptArticleIdsAsList.scala
> +    // var oldArticleId = oldArticle findField { case (n, v) => n == "articleId" }
Fjerne kommentarer.

2020-12-30 10:12 UTC, gunnarvelle commented on src/main/scala/db/migration/V7__ConceptArticleIdsAsList.scala
> +        }*/
Denne også.

2020-12-30 10:12 UTC, gunnarvelle commented on src/test/scala/no/ndla/conceptapi/TestData.scala
> +    api.UpdatedConcept("nb", None, Some("Innhold"), Right(None), None, None, None, None, Some(Seq(42)), None, None)
Ser at gammel kode har 12 men du har brukt 42. Nokon spesiell grunn?

2021-01-04 06:48 UTC, jnatten requested changes
Det eneste "farlige" er den testen med `Deletable`, ellers bare noe småpirk :smiley:

2021-01-04 06:48 UTC, jnatten commented on src/main/scala/db/migration/V7__ConceptArticleIdsAsList.scala
> +    val oldArticle = parse(document).asInstanceOf[JObject]
`mapField` finnes på `JValue`, hvorfor gjør vi denne casten? (`.asInstanceOf[JObject]`)

2021-01-04 06:48 UTC, jnatten commented on src/main/scala/no/ndla/conceptapi/model/api/Concept.scala
> +    @(ApiModelProperty @field)(description = "Article ids to which the concept is connected to") articleIds: Option[Seq[Long]],
Mener at det var noen frontendere som ville at lister alltid skulle være tilstede (bare tomme om det ikke fantes noe data), så da foreslår jeg at denne ikke er `Option` 
```suggestion
    @(ApiModelProperty @field)(description = "Article ids to which the concept is connected to") articleIds: Seq[Long],
```

2021-01-04 06:48 UTC, jnatten commented on src/test/scala/no/ndla/conceptapi/controller/DraftConceptControllerTest.scala
> +    val existingExpected = TestData.emptyApiUpdatedConcept.copy(language = "nb", articleIds = Some(Seq(10)))
Denne testen må nok skrives om til å teste på et annet felt som bruker den `Deletable` typen for å fortsatt teste det samme, feks `metaImage` feltet (Dvs reverte testen til sånn den så ut tidligere og bare bytte ut `articleId` med `metaImage`.

2021-01-05 07:20 UTC, jnatten approved these changes
LGTM! :+1:

2021-01-07 05:54 UTC, merged